import { useState } from 'react'

const ListRender = () => {
  const [list] = useState([
    {
      "nomeCompleto": "AAA USUÁRIO INATIVO",
      "nomeSocial": "INATIVO",
      "dataDeNascimento": "28/02/1979",
      "codigo": 1,
      "sexo": "M",
      "email": "inativo@labtime.ufg.br",
      "estado": "Goiás",
      "municipio": "Goiânia (capital)",
      "numeroDeAcessos": 0,
      "situacao": "Aprovado",
      "dataDeVinculo": "18/06/2018"
    },
    {
      "nomeCompleto": "ACILEGE PEREIRA DOS SANTOS",
      "nomeSocial": "ACILEGE",
      "dataDeNascimento": "04/11/2019",
      "codigo": 2,
      "sexo": "M",
      "email": "acilege@labtime.ufg.br",
      "estado": "Acre",
      "municipio": "Acrelândia",
      "numeroDeAcessos": 0,
      "situacao": "Cancelado",
      "dataDeVinculo": "22/11/2019"
    },
    {
      "nomeCompleto": "ADAICE MARIA GASPAR DE ALMEIDA",
      "nomeSocial": "ADAICE",
      "dataDeNascimento": "13/09/2019",
      "codigo": 3,
      "sexo": "F",
      "email": "rhamoy@gmail.com",
      "estado": "Acre",
      "municipio": "Acrelândia",
      "numeroDeAcessos": 0,
      "situacao": "Ativo",
      "dataDeVinculo": "22/11/2019"
    },
    {
      "nomeCompleto": "ANDREIA MOREIRA BARBOSA",
      "nomeSocial": "ANDREIA",
      "dataDeNascimento": "",
      "codigo": 4,
      "sexo": "",
      "email": "81935544500@labtime.ufg.br",
      "estado": "",
      "municipio": "",
      "numeroDeAcessos": 0,
      "situacao": "Ativo",
      "dataDeVinculo": "08/09/2020"
    },
    {
      "nomeCompleto": "ANIRAM MAIRA BRAS DOS SANTOS",
      "nomeSocial": "ANIRAM",
      "dataDeNascimento": "",
      "codigo": 5,
      "sexo": "",
      "email": "02961413567@labtime.ufg.br",
      "estado": "",
      "municipio": "",
      "numeroDeAcessos": 0,
      "situacao": "Ativo",
      "dataDeVinculo": "08/09/2020"
    },
    {
      "nomeCompleto": "Adelaide da Silva Carvalho Brosig",
      "nomeSocial": "Adelaide Brosig",
      "dataDeNascimento": "11/12/1984",
      "codigo": 6,
      "sexo": "F",
      "email": "adhelaide@gmail.com",
      "estado": "Goiás",
      "municipio": "Goiânia (capital)",
      "numeroDeAcessos": 46,
      "situacao": "Ativo",
      "dataDeVinculo": "22/11/2019"
    },
    {
      "nomeCompleto": "Adelmana maria santos",
      "nomeSocial": "Manamara",
      "dataDeNascimento": "03/05/1978",
      "codigo": 7,
      "sexo": "F",
      "email": "adelmana.maria@labtime.ufg.br",
      "estado": "Alagoas",
      "municipio": "Anadia",
      "numeroDeAcessos": 2,
      "situacao": "Ativo",
      "dataDeVinculo": "09/05/2018"
    },
    {
      "nomeCompleto": "Administrador",
      "nomeSocial": "administrador",
      "dataDeNascimento": "06/03/1998",
      "codigo": 9,
      "sexo": "M",
      "email": "admin@admin.ad",
      "estado": "",
      "municipio": "",
      "numeroDeAcessos": 1,
      "situacao": "Ativo",
      "dataDeVinculo": "03/05/2018"
    },
    {
      "nomeCompleto": "Adonay Tarcisio Marques de Souza",
      "nomeSocial": "Adonay",
      "dataDeNascimento": "28/11/1985",
      "codigo": 10,
      "sexo": "M",
      "email": "teste@hotmail.com",
      "estado": "Goiás",
      "municipio": "Goiânia (capital)",
      "numeroDeAcessos": 0,
      "situacao": "Ativo",
      "dataDeVinculo": "03/05/2018"
    },
    {
      "nomeCompleto": "Adriana maria claudia rogerios",
      "nomeSocial": "Adriana",
      "dataDeNascimento": "08/05/1986",
      "codigo": 11,
      "sexo": "F",
      "email": "adriana@labtime.ufg.br",
      "estado": "Mato Grosso do Sul",
      "municipio": "Campo Grande (capital)",
      "numeroDeAcessos": 13,
      "situacao": "Ativo",
      "dataDeVinculo": "06/07/2020"
    },
    {
      "nomeCompleto": "Alessandra Teste",
      "nomeSocial": "Alessandra",
      "dataDeNascimento": "03/04/1999",
      "codigo": 12,
      "sexo": "M",
      "email": "alessandra_tst@labtime.ufg.br",
      "estado": "Acre",
      "municipio": "Acrelândia",
      "numeroDeAcessos": 0,
      "situacao": "Reprovado",
      "dataDeVinculo": "15/06/2018"
    },
    {
      "nomeCompleto": "Alexandre Mathias Pedro1",
      "nomeSocial": "Alexandre",
      "dataDeNascimento": "30/03/1966",
      "codigo": 13,
      "sexo": "M",
      "email": "alexandrepedro@labtime.ufg.br",
      "estado": "Goiás",
      "municipio": "Goiânia (capital)",
      "numeroDeAcessos": 20,
      "situacao": "",
      "dataDeVinculo": "09/07/2018"
    },
    {
      "nomeCompleto": "Allan Ramalho",
      "nomeSocial": "Allan",
      "dataDeNascimento": "08/03/2018",
      "codigo": 15,
      "sexo": "M",
      "email": "allanramalho@labtime.ufg.br",
      "estado": "",
      "municipio": "",
      "numeroDeAcessos": 0,
      "situacao": "Reprovado",
      "dataDeVinculo": "03/05/2018"
    },
    {
      "nomeCompleto": "Amanda",
      "nomeSocial": "Amanda",
      "dataDeNascimento": "30/12/2011",
      "codigo": 17,
      "sexo": "F",
      "email": "amanda1@labtime.ufg.br",
      "estado": "Goiás",
      "municipio": "Goiânia (capital)",
      "numeroDeAcessos": 0,
      "situacao": "Ativo",
      "dataDeVinculo": "09/05/2018"
    },
    {
      "nomeCompleto": "Amanda Souza",
      "nomeSocial": "Amanda",
      "dataDeNascimento": "07/08/1990",
      "codigo": 18,
      "sexo": "M",
      "email": "amanda@labtime.ufg.br",
      "estado": "Goiás",
      "municipio": "Ipiranga de Goiás",
      "numeroDeAcessos": 0,
      "situacao": "Ativo",
      "dataDeVinculo": "03/05/2018"
    },
    {
      "nomeCompleto": "Ana Clara Rosendo de Sousa",
      "nomeSocial": "Ana",
      "dataDeNascimento": "28/02/1979",
      "codigo": 19,
      "sexo": "F",
      "email": "anaclara@labtime.ufg.br",
      "estado": "Amazonas",
      "municipio": "Pauini",
      "numeroDeAcessos": 2,
      "situacao": "Aprovado",
      "dataDeVinculo": "27/04/2018"
    },
    {
      "nomeCompleto": "Ana Golnçalves",
      "nomeSocial": "Ana",
      "dataDeNascimento": "13/05/2000",
      "codigo": 20,
      "sexo": "F",
      "email": "ana@labtime.ufg.br",
      "estado": "Goiás",
      "municipio": "Pirenópolis",
      "numeroDeAcessos": 0,
      "situacao": "Ativo",
      "dataDeVinculo": "05/07/2018"
    },
    {
      "nomeCompleto": "Andre Soares",
      "nomeSocial": "Andre",
      "dataDeNascimento": "02/03/1990",
      "codigo": 21,
      "sexo": "M",
      "email": "andrekd2@teste.com",
      "estado": "Goiás",
      "municipio": "Goiânia (capital)",
      "numeroDeAcessos": 0,
      "situacao": "Ativo",
      "dataDeVinculo": "27/04/2018"
    },
    {
      "nomeCompleto": "Andrea Cristina Brassaroto",
      "nomeSocial": "Andrea",
      "dataDeNascimento": "28/02/1979",
      "codigo": 22,
      "sexo": "F",
      "email": "andreabrassaroto@labtime.ufg.br",
      "estado": "Amapá",
      "municipio": "Ferreira Gomes",
      "numeroDeAcessos": 16,
      "situacao": "Ativo",
      "dataDeVinculo": "14/06/2018"
    },
    {
      "nomeCompleto": "Antonio sergio baquer de barros",
      "nomeSocial": "Antonio",
      "dataDeNascimento": "05/01/1961",
      "codigo": 23,
      "sexo": "M",
      "email": "sergiobaquer@labtime.ufg.br",
      "estado": "Sergipe",
      "municipio": "Ilha das Flores",
      "numeroDeAcessos": 0,
      "situacao": "",
      "dataDeVinculo": "16/07/2018"
    },
    {
      "nomeCompleto": "Aracelle Vaz Bueno",
      "nomeSocial": "Aracelle",
      "dataDeNascimento": "11/12/1990",
      "codigo": 25,
      "sexo": "F",
      "email": "aracelle2@labtime.ufg.br",
      "estado": "Goiás",
      "municipio": "Santo Antônio de Goiás",
      "numeroDeAcessos": 2,
      "situacao": "Ativo",
      "dataDeVinculo": "13/06/2018"
    },
    {
      "nomeCompleto": "Artur Brosig",
      "nomeSocial": "Brosig",
      "dataDeNascimento": "27/05/1983",
      "codigo": 26,
      "sexo": "M",
      "email": "brosig@labtime.ufg.br",
      "estado": "Goiás",
      "municipio": "Goiânia (capital)",
      "numeroDeAcessos": 4,
      "situacao": "Reprovado",
      "dataDeVinculo": "07/06/2018"
    },
    {
      "nomeCompleto": "Athos Araújo da Silva",
      "nomeSocial": "Athos",
      "dataDeNascimento": "10/08/2007",
      "codigo": 30,
      "sexo": "F",
      "email": "athos@labtime.ufg.br",
      "estado": "Goiás",
      "municipio": "Goiânia (capital)",
      "numeroDeAcessos": 0,
      "situacao": "Cancelado",
      "dataDeVinculo": "17/07/2018"
    },
    {
      "nomeCompleto": "Audecir silva dos santos",
      "nomeSocial": "Audecir",
      "dataDeNascimento": "29/06/2002",
      "codigo": 31,
      "sexo": "M",
      "email": "audecirsantos@labtime.ufg.br",
      "estado": "Amazonas",
      "municipio": "Anamã",
      "numeroDeAcessos": 0,
      "situacao": "Ativo",
      "dataDeVinculo": "05/07/2018"
    },
    {
      "nomeCompleto": "Biagy Oliveira",
      "nomeSocial": "Biagy",
      "dataDeNascimento": "",
      "codigo": 32,
      "sexo": "",
      "email": "biagy2@labtime.ufg.br",
      "estado": "",
      "municipio": "",
      "numeroDeAcessos": 0,
      "situacao": "Ativo",
      "dataDeVinculo": "03/05/2018"
    },
    {
      "nomeCompleto": "Bruce Wayne",
      "nomeSocial": "Batman",
      "dataDeNascimento": "02/03/1990",
      "codigo": 33,
      "sexo": "M",
      "email": "bruce@labtime.ufg.br",
      "estado": "Goiás",
      "municipio": "Goiânia (capital)",
      "numeroDeAcessos": 0,
      "situacao": "Ativo",
      "dataDeVinculo": "03/05/2018"
    },
    {
      "nomeCompleto": "Bruna Golnçalves",
      "nomeSocial": "Bruna",
      "dataDeNascimento": "13/05/2000",
      "codigo": 34,
      "sexo": "F",
      "email": "bruna@labtime.ufg.br",
      "estado": "Goiás",
      "municipio": "Pirenópolis",
      "numeroDeAcessos": 0,
      "situacao": "Ativo",
      "dataDeVinculo": "17/07/2018"
    },
    {
      "nomeCompleto": "CASSIUS ANDRE MACHADO PORTO",
      "nomeSocial": "CASSIUS",
      "dataDeNascimento": "",
      "codigo": 35,
      "sexo": "",
      "email": "96947950520@labtime.ufg.br",
      "estado": "",
      "municipio": "",
      "numeroDeAcessos": 0,
      "situacao": "Ativo",
      "dataDeVinculo": "08/09/2020"
    },
    {
      "nomeCompleto": "Carlos Eduardo",
      "nomeSocial": "Carlos",
      "dataDeNascimento": "12/07/2018",
      "codigo": 36,
      "sexo": "M",
      "email": "carlosedu@labtime.ufg.br",
      "estado": "Goiás",
      "municipio": "Abadia de Goiás",
      "numeroDeAcessos": 0,
      "situacao": "Ativo",
      "dataDeVinculo": "03/05/2018"
    },
    {
      "nomeCompleto": "Catarine Santana Cardoso Jesus",
      "nomeSocial": "Catarine",
      "dataDeNascimento": "",
      "codigo": 37,
      "sexo": "",
      "email": "05069845594@labtime.ufg.br",
      "estado": "",
      "municipio": "",
      "numeroDeAcessos": 0,
      "situacao": "Ativo",
      "dataDeVinculo": "08/09/2020"
    },
    {
      "nomeCompleto": "Cesar Augusto",
      "nomeSocial": "Cesar",
      "dataDeNascimento": "21/12/2012",
      "codigo": 38,
      "sexo": "M",
      "email": "cesara@labtime.ufg.br",
      "estado": "Goiás",
      "municipio": "Goiânia (capital)",
      "numeroDeAcessos": 0,
      "situacao": "Ativo",
      "dataDeVinculo": "02/07/2020"
    },
    {
      "nomeCompleto": "Cícero teixeira carneiro",
      "nomeSocial": "Cícero",
      "dataDeNascimento": "02/02/1993",
      "codigo": 39,
      "sexo": "M",
      "email": "texcicero@labtime.ufg.br",
      "estado": "Amapá",
      "municipio": "Itaubal",
      "numeroDeAcessos": 0,
      "situacao": "Ativo",
      "dataDeVinculo": "15/06/2018"
    },
    {
      "nomeCompleto": "Daniel Cordeiro da Silva Filho",
      "nomeSocial": "Daniel",
      "dataDeNascimento": "",
      "codigo": 40,
      "sexo": "",
      "email": "danielcordeiro@labtime.ufg.br",
      "estado": "",
      "municipio": "",
      "numeroDeAcessos": 0,
      "situacao": "Ativo",
      "dataDeVinculo": "03/05/2018"
    },
    {
      "nomeCompleto": "Djean Araujo",
      "nomeSocial": "Djean",
      "dataDeNascimento": "31/12/2015",
      "codigo": 41,
      "sexo": "M",
      "email": "djean@labtime.ufg.br",
      "estado": "Acre",
      "municipio": "Acrelândia",
      "numeroDeAcessos": 0,
      "situacao": "Ativo",
      "dataDeVinculo": "03/05/2018"
    },
    {
      "nomeCompleto": "Donizete monteiro da silva",
      "nomeSocial": "Donizete",
      "dataDeNascimento": "12/05/1988",
      "codigo": 42,
      "sexo": "M",
      "email": "donizeteacre@labtime.ufg.br",
      "estado": "São Paulo",
      "municipio": "Roseira",
      "numeroDeAcessos": 1,
      "situacao": "Ativo",
      "dataDeVinculo": "17/08/2018"
    },
    {
      "nomeCompleto": "Emilia Brosig",
      "nomeSocial": "Emilia",
      "dataDeNascimento": "03/08/0980",
      "codigo": 43,
      "sexo": "F",
      "email": "adhelaide1@gmail.com",
      "estado": "Goiás",
      "municipio": "Pirenópolis",
      "numeroDeAcessos": 0,
      "situacao": "Ativo",
      "dataDeVinculo": "19/04/2018"
    },
    {
      "nomeCompleto": "Felícia Teste",
      "nomeSocial": "Felícia",
      "dataDeNascimento": "03/04/1999",
      "codigo": 44,
      "sexo": "M",
      "email": "felcia11351_tst47@labtime.ufg.br",
      "estado": "Acre",
      "municipio": "Acrelândia",
      "numeroDeAcessos": 2,
      "situacao": "Ativo",
      "dataDeVinculo": "12/07/2018"
    },
    {
      "nomeCompleto": "Fernanda Cristina de Sousa",
      "nomeSocial": "Fernanda",
      "dataDeNascimento": "12/01/1992",
      "codigo": 45,
      "sexo": "F",
      "email": "fernanda@labtime.ufg.br",
      "estado": "Goiás",
      "municipio": "Goiânia (capital)",
      "numeroDeAcessos": 0,
      "situacao": "Ativo",
      "dataDeVinculo": "03/05/2018"
    },
    {
      "nomeCompleto": "Florzinha",
      "nomeSocial": "Florzinha",
      "dataDeNascimento": "10/03/1990",
      "codigo": 46,
      "sexo": "F",
      "email": "florzinha@labtime.ufg.br",
      "estado": "Goiás",
      "municipio": "Goiânia (capital)",
      "numeroDeAcessos": 0,
      "situacao": "",
      "dataDeVinculo": "26/06/2018"
    },
    {
      "nomeCompleto": "Francisco",
      "nomeSocial": "Francisco",
      "dataDeNascimento": "07/08/1990",
      "codigo": 47,
      "sexo": "M",
      "email": "francisco@labtime.ufg.br",
      "estado": "Goiás",
      "municipio": "Ipiranga de Goiás",
      "numeroDeAcessos": 0,
      "situacao": "Aprovado",
      "dataDeVinculo": "03/05/2018"
    },
    {
      "nomeCompleto": "Gabriella",
      "nomeSocial": "Gabriella",
      "dataDeNascimento": "02/03/1990",
      "codigo": 48,
      "sexo": "F",
      "email": "gabi@labtime.ufg.br",
      "estado": "Goiás",
      "municipio": "Goiânia (capital)",
      "numeroDeAcessos": 0,
      "situacao": "Aprovado",
      "dataDeVinculo": "03/05/2018"
    },
    {
      "nomeCompleto": "Geovana",
      "nomeSocial": "Geovana",
      "dataDeNascimento": "07/08/1990",
      "codigo": 49,
      "sexo": "M",
      "email": "geovana@labtime.ufg.br",
      "estado": "Goiás",
      "municipio": "Ipiranga de Goiás",
      "numeroDeAcessos": 0,
      "situacao": "Ativo",
      "dataDeVinculo": "27/04/2018"
    },
    {
      "nomeCompleto": "Gohan",
      "nomeSocial": "Gohan",
      "dataDeNascimento": "08/10/1990",
      "codigo": 50,
      "sexo": "M",
      "email": "gohan@labtime.ufg.br",
      "estado": "Ceará",
      "municipio": "Ipaumirim",
      "numeroDeAcessos": 0,
      "situacao": "Ativo",
      "dataDeVinculo": "16/06/2020"
    },
    {
      "nomeCompleto": "Hugo Strange",
      "nomeSocial": "Hugo Strange",
      "dataDeNascimento": "11/03/1996",
      "codigo": 51,
      "sexo": "M",
      "email": "bruno@labtime.ufg.br",
      "estado": "",
      "municipio": "",
      "numeroDeAcessos": 1,
      "situacao": "Ativo",
      "dataDeVinculo": "04/05/2018"
    },
    {
      "nomeCompleto": "Igor Avelar",
      "nomeSocial": "Igor",
      "dataDeNascimento": "",
      "codigo": 52,
      "sexo": "",
      "email": "igoravelar@labtime.ufg.br",
      "estado": "",
      "municipio": "",
      "numeroDeAcessos": 0,
      "situacao": "Ativo",
      "dataDeVinculo": "03/05/2018"
    },
    {
      "nomeCompleto": "Igor Mael",
      "nomeSocial": "Igor",
      "dataDeNascimento": "07/08/1990",
      "codigo": 54,
      "sexo": "M",
      "email": "igormael@labtime.ufg.br",
      "estado": "Goiás",
      "municipio": "Ipiranga de Goiás",
      "numeroDeAcessos": 0,
      "situacao": "Ativo",
      "dataDeVinculo": "03/05/2018"
    },
    {
      "nomeCompleto": "Isis Carvalho",
      "nomeSocial": "Isis",
      "dataDeNascimento": "",
      "codigo": 55,
      "sexo": "",
      "email": "isis@labtime.ufg.br",
      "estado": "",
      "municipio": "",
      "numeroDeAcessos": 0,
      "situacao": "Ativo",
      "dataDeVinculo": "03/05/2018"
    },
    {
      "nomeCompleto": "Janis Joplin",
      "nomeSocial": "Janis Joplin",
      "dataDeNascimento": "30/04/1990",
      "codigo": 56,
      "sexo": "F",
      "email": "janisjoplin@labtime.com",
      "estado": "Goiás",
      "municipio": "Nerópolis",
      "numeroDeAcessos": 0,
      "situacao": "Reprovado",
      "dataDeVinculo": "03/05/2018"
    },
    {
      "nomeCompleto": "Jeniffer Silva",
      "nomeSocial": "Jeniffer",
      "dataDeNascimento": "21/04/1995",
      "codigo": 58,
      "sexo": "F",
      "email": "jenifferspm@gmail.com",
      "estado": "Goiás",
      "municipio": "Goiânia (capital)",
      "numeroDeAcessos": 0,
      "situacao": "Cancelado",
      "dataDeVinculo": "27/04/2018"
    },
    {
      "nomeCompleto": "Joana",
      "nomeSocial": "Joana",
      "dataDeNascimento": "21/05/2010",
      "codigo": 59,
      "sexo": "F",
      "email": "joana@labtime.ufg.br",
      "estado": "Bahia",
      "municipio": "Anguera",
      "numeroDeAcessos": 0,
      "situacao": "Ativo",
      "dataDeVinculo": "03/05/2018"
    },
    {
      "nomeCompleto": "Joao da Silva",
      "nomeSocial": "Joao",
      "dataDeNascimento": "",
      "codigo": 60,
      "sexo": "",
      "email": "joao@dominio.com.br",
      "estado": "",
      "municipio": "",
      "numeroDeAcessos": 0,
      "situacao": "Ativo",
      "dataDeVinculo": "02/09/2020"
    },
    {
      "nomeCompleto": "Johny Cash",
      "nomeSocial": "Johny Cash",
      "dataDeNascimento": "12/03/1996",
      "codigo": 61,
      "sexo": "M",
      "email": "cash@labtime.ufg.br",
      "estado": "Bahia",
      "municipio": "Chorrochó",
      "numeroDeAcessos": 0,
      "situacao": "Cancelado",
      "dataDeVinculo": "03/05/2018"
    },
    {
      "nomeCompleto": "Jose",
      "nomeSocial": "Jose",
      "dataDeNascimento": "07/08/1990",
      "codigo": 63,
      "sexo": "M",
      "email": "jose@labtime.ufg.br",
      "estado": "Goiás",
      "municipio": "Ipiranga de Goiás",
      "numeroDeAcessos": 0,
      "situacao": "Ativo",
      "dataDeVinculo": "03/05/2018"
    },
    {
      "nomeCompleto": "João Braz",
      "nomeSocial": "João",
      "dataDeNascimento": "",
      "codigo": 64,
      "sexo": "",
      "email": "joaobraz@labtime.ufg.br",
      "estado": "",
      "municipio": "",
      "numeroDeAcessos": 0,
      "situacao": "Ativo",
      "dataDeVinculo": "03/05/2018"
    },
    {
      "nomeCompleto": "KERLYVAINY PEREIRA VARGAS",
      "nomeSocial": "KERLYVAINY",
      "dataDeNascimento": "28/02/1979",
      "codigo": 65,
      "sexo": "",
      "email": "kerlyvainy@labtime.ufg.br",
      "estado": "",
      "municipio": "",
      "numeroDeAcessos": 0,
      "situacao": "Ativo",
      "dataDeVinculo": "27/04/2018"
    },
    {
      "nomeCompleto": "Leo Santana",
      "nomeSocial": "LS",
      "dataDeNascimento": "01/02/1992",
      "codigo": 66,
      "sexo": "M",
      "email": "leosantana@labtime.ufg.br",
      "estado": "Goiás",
      "municipio": "Goiânia (capital)",
      "numeroDeAcessos": 0,
      "situacao": "Ativo",
      "dataDeVinculo": "03/05/2018"
    },
    {
      "nomeCompleto": "Lex Luthor",
      "nomeSocial": "Lex Luthor",
      "dataDeNascimento": "02/03/1990",
      "codigo": 68,
      "sexo": "M",
      "email": "lex@labtime.com",
      "estado": "Goiás",
      "municipio": "Goiânia (capital)",
      "numeroDeAcessos": 0,
      "situacao": "Ativo",
      "dataDeVinculo": "03/05/2018"
    },
    {
      "nomeCompleto": "Linda Macedo",
      "nomeSocial": "Linda",
      "dataDeNascimento": "01/03/1979",
      "codigo": 69,
      "sexo": "M",
      "email": "linda@labtime.ufg.br",
      "estado": "Amapá",
      "municipio": "Cutias",
      "numeroDeAcessos": 0,
      "situacao": "Ativo",
      "dataDeVinculo": "03/05/2018"
    },
    {
      "nomeCompleto": "Lindinha",
      "nomeSocial": "Lindinha",
      "dataDeNascimento": "10/04/1990",
      "codigo": 70,
      "sexo": "F",
      "email": "lindinha@labtime.ufg.br",
      "estado": "Acre",
      "municipio": "Acrelândia",
      "numeroDeAcessos": 0,
      "situacao": "Ativo",
      "dataDeVinculo": "14/05/2020"
    },
    {
      "nomeCompleto": "Lucas Faro",
      "nomeSocial": "Lucas",
      "dataDeNascimento": "10/06/1986",
      "codigo": 71,
      "sexo": "M",
      "email": "lucasfaro@labtime.ufg.br",
      "estado": "Amapá",
      "municipio": "Serra do Navio",
      "numeroDeAcessos": 1,
      "situacao": "Ativo",
      "dataDeVinculo": "16/08/2018"
    },
    {
      "nomeCompleto": "Ludmila Toledo",
      "nomeSocial": "Ludmila",
      "dataDeNascimento": "07/04/1988",
      "codigo": 72,
      "sexo": "F",
      "email": "ludmila_@labtime.ufg.br",
      "estado": "Goiás",
      "municipio": "Goiânia (capital)",
      "numeroDeAcessos": 3,
      "situacao": "Ativo",
      "dataDeVinculo": "12/06/2018"
    },
    {
      "nomeCompleto": "Luna Brosig",
      "nomeSocial": "Luna Brosig",
      "dataDeNascimento": "21/04/2014",
      "codigo": 73,
      "sexo": "F",
      "email": "luna@labtime.ufg.br",
      "estado": "Goiás",
      "municipio": "Goiânia (capital)",
      "numeroDeAcessos": 36,
      "situacao": "Aprovado",
      "dataDeVinculo": "16/04/2018"
    },
    {
      "nomeCompleto": "MIRCINEIA EVANGELISTA DE OLIVEIRA VIEIRA",
      "nomeSocial": "MIRCINEIA",
      "dataDeNascimento": "28/02/1979",
      "codigo": 74,
      "sexo": "",
      "email": "emaureli@labtime.ufg.br",
      "estado": "",
      "municipio": "",
      "numeroDeAcessos": 0,
      "situacao": "Ativo",
      "dataDeVinculo": "27/04/2018"
    },
    {
      "nomeCompleto": "Marcel Oliveira",
      "nomeSocial": "Marcel",
      "dataDeNascimento": "",
      "codigo": 75,
      "sexo": "",
      "email": "marcel@labtime.ufg.br",
      "estado": "",
      "municipio": "",
      "numeroDeAcessos": 0,
      "situacao": "Ativo",
      "dataDeVinculo": "17/08/2018"
    },
    {
      "nomeCompleto": "Marcela Valença",
      "nomeSocial": "Marcela",
      "dataDeNascimento": "",
      "codigo": 76,
      "sexo": "",
      "email": "marcelaval@labtime.ufg.br",
      "estado": "",
      "municipio": "",
      "numeroDeAcessos": 0,
      "situacao": "Ativo",
      "dataDeVinculo": "16/08/2018"
    },
    {
      "nomeCompleto": "Marcos Ribeiro",
      "nomeSocial": "Marcos",
      "dataDeNascimento": "05/08/1982",
      "codigo": 77,
      "sexo": "M",
      "email": "marcosribeiro@labtime.ufg.br",
      "estado": "Amapá",
      "municipio": "Cutias",
      "numeroDeAcessos": 0,
      "situacao": "Ativo",
      "dataDeVinculo": "09/05/2018"
    },
    {
      "nomeCompleto": "Marcos alexandre correia de oliveira",
      "nomeSocial": "Marcos",
      "dataDeNascimento": "03/03/1990",
      "codigo": 78,
      "sexo": "M",
      "email": "nemesisrepk@labtime.ufg.br",
      "estado": "",
      "municipio": "",
      "numeroDeAcessos": 0,
      "situacao": "Ativo",
      "dataDeVinculo": "09/05/2018"
    },
    {
      "nomeCompleto": "Margarida Paula",
      "nomeSocial": "Margarida",
      "dataDeNascimento": "",
      "codigo": 79,
      "sexo": "",
      "email": "margarida@labtime.ufg.br",
      "estado": "",
      "municipio": "",
      "numeroDeAcessos": 0,
      "situacao": "Ativo",
      "dataDeVinculo": "03/05/2018"
    },
    {
      "nomeCompleto": "Maria Rodrigues",
      "nomeSocial": "Maria",
      "dataDeNascimento": "",
      "codigo": 80,
      "sexo": "",
      "email": "maria@dominio.com",
      "estado": "",
      "municipio": "",
      "numeroDeAcessos": 0,
      "situacao": "Ativo",
      "dataDeVinculo": "02/09/2020"
    },
    {
      "nomeCompleto": "Marina Campos",
      "nomeSocial": "Marina",
      "dataDeNascimento": "24/01/1983",
      "codigo": 81,
      "sexo": "F",
      "email": "marina@labtime.ufg.br",
      "estado": "Ceará",
      "municipio": "Acaraú",
      "numeroDeAcessos": 1,
      "situacao": "Ativo",
      "dataDeVinculo": "06/07/2020"
    },
    {
      "nomeCompleto": "Marisa Carvalho",
      "nomeSocial": "Marisa Carvalho",
      "dataDeNascimento": "04/01/1961",
      "codigo": 82,
      "sexo": "F",
      "email": "contato@pousadacarvalho.com.br",
      "estado": "Goiás",
      "municipio": "Pirenópolis",
      "numeroDeAcessos": 0,
      "situacao": "Ativo",
      "dataDeVinculo": "03/05/2018"
    },
    {
      "nomeCompleto": "Martin Luther King",
      "nomeSocial": "Martin Luther King",
      "dataDeNascimento": "12/02/2000",
      "codigo": 83,
      "sexo": "M",
      "email": "martin@labtime.com",
      "estado": "Acre",
      "municipio": "Acrelândia",
      "numeroDeAcessos": 0,
      "situacao": "Ativo",
      "dataDeVinculo": "03/05/2018"
    },
    {
      "nomeCompleto": "Matheus Vinicius Dias Ribeiro",
      "nomeSocial": "Matheus Dias",
      "dataDeNascimento": "07/02/1999",
      "codigo": 84,
      "sexo": "M",
      "email": "matheusribeiro@labtime.ufg.br",
      "estado": "Goiás",
      "municipio": "Goiânia (capital)",
      "numeroDeAcessos": 0,
      "situacao": "Ativo",
      "dataDeVinculo": "23/04/2020"
    },
    {
      "nomeCompleto": "Mauricio",
      "nomeSocial": "Mauricio",
      "dataDeNascimento": "",
      "codigo": 85,
      "sexo": "",
      "email": "labtime.dev@gmail.com",
      "estado": "",
      "municipio": "",
      "numeroDeAcessos": 0,
      "situacao": "Ativo",
      "dataDeVinculo": "02/05/2018"
    },
    {
      "nomeCompleto": "Morgana",
      "nomeSocial": "Morgana",
      "dataDeNascimento": "",
      "codigo": 86,
      "sexo": "",
      "email": "morgana@labtime.ufg.br",
      "estado": "",
      "municipio": "",
      "numeroDeAcessos": 0,
      "situacao": "Ativo",
      "dataDeVinculo": "03/05/2018"
    },
    {
      "nomeCompleto": "Noah Silva",
      "nomeSocial": "Noah",
      "dataDeNascimento": "",
      "codigo": 87,
      "sexo": "",
      "email": "noah@labtime.ufg.br",
      "estado": "",
      "municipio": "",
      "numeroDeAcessos": 0,
      "situacao": "Ativo",
      "dataDeVinculo": "16/08/2018"
    },
    {
      "nomeCompleto": "Pablo Brunet",
      "nomeSocial": "Pablo",
      "dataDeNascimento": "10/11/2001",
      "codigo": 88,
      "sexo": "M",
      "email": "pablo@labtime.ufg.br",
      "estado": "Bahia",
      "municipio": "Barrocas",
      "numeroDeAcessos": 0,
      "situacao": "Cancelado",
      "dataDeVinculo": "03/05/2018"
    },
    {
      "nomeCompleto": "Paulo Henrique de Aguiar Medeiros",
      "nomeSocial": "Paulo",
      "dataDeNascimento": "14/04/1985",
      "codigo": 89,
      "sexo": "M",
      "email": "galfano@labtime.ufg.br",
      "estado": "Goiás",
      "municipio": "Goiânia (capital)",
      "numeroDeAcessos": 0,
      "situacao": "Ativo",
      "dataDeVinculo": "03/05/2018"
    },
    {
      "nomeCompleto": "Pedro",
      "nomeSocial": "Pedro",
      "dataDeNascimento": "07/08/1990",
      "codigo": 90,
      "sexo": "M",
      "email": "pedro@labtime.ufg.br",
      "estado": "Goiás",
      "municipio": "Ipiranga de Goiás",
      "numeroDeAcessos": 0,
      "situacao": "Ativo",
      "dataDeVinculo": "27/04/2018"
    },
    {
      "nomeCompleto": "Pedro Vinícius",
      "nomeSocial": "pedro",
      "dataDeNascimento": "28/01/2001",
      "codigo": 91,
      "sexo": "M",
      "email": "pedrovovp@labtime.ufg.br",
      "estado": "Goiás",
      "municipio": "Goiânia (capital)",
      "numeroDeAcessos": 0,
      "situacao": "Ativo",
      "dataDeVinculo": "14/04/2020"
    },
    {
      "nomeCompleto": "Percival Brosig",
      "nomeSocial": "Perci",
      "dataDeNascimento": "14/02/1949",
      "codigo": 92,
      "sexo": "M",
      "email": "percival@labtime.ufg.br",
      "estado": "São Paulo",
      "municipio": "São Paulo (capital)",
      "numeroDeAcessos": 0,
      "situacao": "Ativo",
      "dataDeVinculo": "03/05/2018"
    },
    {
      "nomeCompleto": "Peter Parker",
      "nomeSocial": "Spider-Man",
      "dataDeNascimento": "02/03/1990",
      "codigo": 93,
      "sexo": "M",
      "email": "peter@labtime.ufg.br",
      "estado": "Goiás",
      "municipio": "Goiânia (capital)",
      "numeroDeAcessos": 0,
      "situacao": "Ativo",
      "dataDeVinculo": "04/05/2018"
    },
    {
      "nomeCompleto": "Rafael Carvalho",
      "nomeSocial": "Rhamoy Rhandy",
      "dataDeNascimento": "01/04/1980",
      "codigo": 94,
      "sexo": "M",
      "email": "rhandyrafhael@gmail.com",
      "estado": "Goiás",
      "municipio": "Bela Vista de Goiás",
      "numeroDeAcessos": 1,
      "situacao": "Cancelado",
      "dataDeVinculo": "02/05/2018"
    },
    {
      "nomeCompleto": "Raquel Silva",
      "nomeSocial": "Raquel",
      "dataDeNascimento": "",
      "codigo": 96,
      "sexo": "",
      "email": "raquel@labtime.ufg.br",
      "estado": "",
      "municipio": "",
      "numeroDeAcessos": 0,
      "situacao": "Ativo",
      "dataDeVinculo": "03/05/2018"
    },
    {
      "nomeCompleto": "Rebeca Figueira",
      "nomeSocial": "Rebeca",
      "dataDeNascimento": "",
      "codigo": 97,
      "sexo": "",
      "email": "rebeca@labtime.ufg.br",
      "estado": "",
      "municipio": "",
      "numeroDeAcessos": 0,
      "situacao": "Ativo",
      "dataDeVinculo": "17/08/2018"
    },
    {
      "nomeCompleto": "Rhandoufo Carvalho",
      "nomeSocial": "Rhandoufo",
      "dataDeNascimento": "31/12/1995",
      "codigo": 98,
      "sexo": "M",
      "email": "rhamoy1@gmail.com",
      "estado": "Acre",
      "municipio": "Acrelândia",
      "numeroDeAcessos": 0,
      "situacao": "Ativo",
      "dataDeVinculo": "02/05/2018"
    },
    {
      "nomeCompleto": "Rhandy Rafahel de Carvalho",
      "nomeSocial": "Rhandy",
      "dataDeNascimento": "07/08/1990",
      "codigo": 99,
      "sexo": "M",
      "email": "rhandy@labtime.ufg.br",
      "estado": "Goiás",
      "municipio": "Ipiranga de Goiás",
      "numeroDeAcessos": 20,
      "situacao": "Ativo",
      "dataDeVinculo": "02/05/2018"
    },
    {
      "nomeCompleto": "Rodrigo Castro",
      "nomeSocial": "Rodrigo",
      "dataDeNascimento": "15/07/1976",
      "codigo": 101,
      "sexo": "M",
      "email": "rodrigo@labtime.ufg.br",
      "estado": "Sergipe",
      "municipio": "Gracho Cardoso",
      "numeroDeAcessos": 0,
      "situacao": "Ativo",
      "dataDeVinculo": "03/05/2018"
    },
    {
      "nomeCompleto": "SIMONE MARCIELLY DE OLIVEIRA",
      "nomeSocial": "SIMONE",
      "dataDeNascimento": "28/02/1979",
      "codigo": 102,
      "sexo": "",
      "email": "marcielysimone@labtime.ufg.br",
      "estado": "",
      "municipio": "",
      "numeroDeAcessos": 0,
      "situacao": "Ativo",
      "dataDeVinculo": "27/04/2018"
    },
    {
      "nomeCompleto": "Santiago",
      "nomeSocial": "Santiago",
      "dataDeNascimento": "28/02/1979",
      "codigo": 103,
      "sexo": "M",
      "email": "kelvin@labtime.ufg.br",
      "estado": "Maranhão",
      "municipio": "Altamira do Maranhão",
      "numeroDeAcessos": 0,
      "situacao": "Cancelado",
      "dataDeVinculo": "27/04/2018"
    },
    {
      "nomeCompleto": "Sol",
      "nomeSocial": "Sol",
      "dataDeNascimento": "19/08/2017",
      "codigo": 104,
      "sexo": "M",
      "email": "adelaidebrosig@gmail.com",
      "estado": "Goiás",
      "municipio": "Goiânia (capital)",
      "numeroDeAcessos": 6,
      "situacao": "Ativo",
      "dataDeVinculo": "09/10/2019"
    },
    {
      "nomeCompleto": "Tony Stark",
      "nomeSocial": "Tony Stark",
      "dataDeNascimento": "30/04/1990",
      "codigo": 105,
      "sexo": "M",
      "email": "tony@labtime.ufg.br",
      "estado": "Paraíba",
      "municipio": "Curral de Cima",
      "numeroDeAcessos": 0,
      "situacao": "Reprovado",
      "dataDeVinculo": "27/04/2018"
    },
    {
      "nomeCompleto": "Téo",
      "nomeSocial": "Téo",
      "dataDeNascimento": "16/05/1990",
      "codigo": 106,
      "sexo": "M",
      "email": "teo@labtime.ufg.br",
      "estado": "",
      "municipio": "",
      "numeroDeAcessos": 0,
      "situacao": "Ativo",
      "dataDeVinculo": "03/05/2018"
    },
    {
      "nomeCompleto": "Valmir",
      "nomeSocial": "Valmir",
      "dataDeNascimento": "28/02/1979",
      "codigo": 107,
      "sexo": "",
      "email": "valmir@labtime.ufg.br",
      "estado": "",
      "municipio": "",
      "numeroDeAcessos": 0,
      "situacao": "Ativo",
      "dataDeVinculo": "27/04/2018"
    },
    {
      "nomeCompleto": "Yuri Marques",
      "nomeSocial": "Yuri",
      "dataDeNascimento": "01/01/2019",
      "codigo": 108,
      "sexo": "M",
      "email": "yuri@labtime.ufg.br",
      "estado": "Amapá",
      "municipio": "Amapá",
      "numeroDeAcessos": 0,
      "situacao": "Ativo",
      "dataDeVinculo": "03/05/2018"
    },
    {
      "nomeCompleto": "calila de jesus pereira",
      "nomeSocial": "calila",
      "dataDeNascimento": "",
      "codigo": 109,
      "sexo": "",
      "email": "06301466594@labtime.ufg.br",
      "estado": "",
      "municipio": "",
      "numeroDeAcessos": 0,
      "situacao": "Ativo",
      "dataDeVinculo": "08/09/2020"
    },
    {
      "nomeCompleto": "fulano novo",
      "nomeSocial": "fulano",
      "dataDeNascimento": "28/02/1979",
      "codigo": 110,
      "sexo": "",
      "email": "fulano@labtime.ufg.br",
      "estado": "",
      "municipio": "",
      "numeroDeAcessos": 0,
      "situacao": "Reprovado",
      "dataDeVinculo": "03/05/2018"
    },
    {
      "nomeCompleto": "jonathas eloi",
      "nomeSocial": "Jonathas",
      "dataDeNascimento": "13/11/1994",
      "codigo": 111,
      "sexo": "M",
      "email": "jonathaseloi@gmail.com",
      "estado": "Alagoas",
      "municipio": "Anadia",
      "numeroDeAcessos": 1,
      "situacao": "Ativo",
      "dataDeVinculo": "03/05/2018"
    }
  ]);
  return (
    <div>
      <ul>
        {list.map((item) => (
          <li key={item.codigo}>
            -- Nome Completo: {item.nomeCompleto}
            || Nome Social: {item.nomeSocial}
            || Data de Nascimento: {item.dataDeNascimento}
            || Código: {item.codigo}
            || Sexo: {item.sexo}
            || E-mail: {item.email}
            || Estado: {item.estado}
            || Município: {item.municipio}
            || Numero de Acessos: {item.numeroDeAcessos}
            || Situação: {item.situacao}
            || Data de Vinculo: {item.dataDeVinculo}
          </li>
        ))}
      </ul>
    </div>
  )
}

export default ListRender;